{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orderflow.secretName" . }}
  labels:
    {{- include "orderflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-secret: {{ .Values.secrets.adminSecret | quote }}
  action-secret: {{ .Values.secrets.actionSecret | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  keycloak-admin-password: {{ .Values.secrets.keycloakAdminPassword | quote }}
  nextauth-secret: {{ .Values.web.nextauthSecret | quote }}
{{- end }}
