{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orderflow.name" . }}-web
  labels:
    {{- include "orderflow.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "orderflow.name" . }}-web
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orderflow.name" . }}-web
  labels:
    {{- include "orderflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "orderflow.name" . }}-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "orderflow.name" . }}-web
    spec:
      containers:
        - name: web
          image: {{ .Values.images.web }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          env:
            - name: NEXTAUTH_URL
              value: {{ .Values.web.nextauthUrl | default "http://localhost:3000" | quote }}
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef: { name: {{ include "orderflow.secretName" . }}, key: nextauth-secret }
            - name: KEYCLOAK_ISSUER
              value: {{ .Values.web.keycloakIssuer | default (printf "http://%s-keycloak:8080/realms/ecommerce-orderflow" (include "orderflow.name" .)) | quote }}
            - name: KEYCLOAK_CLIENT_ID
              value: web
            - name: NEXT_PUBLIC_GRAPHQL_URL
              value: {{ .Values.web.publicGraphqlUrl | quote }}
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet: { path: /login, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
{{- end }}
